# Generated by Django 5.0.2 on 2024-02-25 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_remove_course_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='title',
            new_name='title_course',
        ),
    ]
