# Generated by Django 5.0.2 on 2024-02-25 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_rename_title_course_title_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='title_course',
            new_name='title',
        ),
    ]
