# Generated by Django 5.0.2 on 2024-02-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_remove_course_category_course_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='course',
            field=models.ManyToManyField(to='course.course'),
        ),
    ]
